leanprover/LNSym

Arm/Memory.lean
Arm/State.lean
Proofs/MultiInsts.lean
Proofs/Sha512_block_armv8.lean
Tactics/Sym.lean

A macro-style tactic is chosen instead of the monad style so that developers can easily extend the tactics. However, this will change for a small set of tactics if they need more fine-grained manipulations.

Split sym1 into smaller tactics

---

Arm/Decode.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/Cosim/platform_check.sh
Arm/Insts/DPSFP/Crypto_four_reg.lean
Arm/Insts/DPSFP/Crypto_three_reg_sha512.lean
Arm/Insts/DPSFP/Crypto_two_reg_sha512.lean
Arm/Insts/DPSFP/Insts.lean

Add EOR3 instruction which is part of the Cryptographic four-register group of DPSFP
https://developer.arm.com/documentation/ddi0602/2023-12/SIMD-FP-Instructions/EOR3--Three-way-Exclusive-OR-?lang=en
Also place the shabang line at the top of the shell script `platform_check.sh`. Otherwise, aarch64 is not detected.
`make all` including conformance testing.

EOR3, part of Crypto four registers.

---

Arm/Decode.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/Common.lean
Arm/Insts/DPSFP/Advanced_simd_copy.lean
Arm/Insts/DPSFP/Advanced_simd_modified_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_scalar_copy.lean
Arm/Insts/DPSFP/Advanced_simd_three_different.lean
Arm/Insts/DPSFP/Advanced_simd_three_same.lean
Arm/Insts/DPSFP/Insts.lean

This PR adds supports for:
1. Advanced SIMD Modified Immediate instructions including `MOVI, MVNI, ORR, BIC (Immediate, vector) and FMOV (vector, immediate, single/double-precision)`
2. Advanced SIMD Scalar Copy instructions including `DUP (element, scalar)`
3. Advanced SIMD Copy instructions including `DUP (element vector, general), INS (element, general), SMOV (32-, 64-bit) and UMOV (32-, 64-bit)`
4. Refactors proofs involving `hi - lo + 1 = esize` and `esize > 0`.
The `make all` succeeds and conformance testing succeeds on both Graviton2 and Graviton3 machines 

Adding MOV related instructions

---

Arm/Decode/DPI.lean
Arm/Exec.lean
Arm/Insts/DPI/Add_sub_imm.lean
Arm/Insts/DPI/Bitfield.lean
Arm/Insts/DPI/Insts.lean
Arm/Insts/DPI/Logical_imm.lean
Arm/Insts/DPSFP/Crypto_four_reg.lean

Add LSR instruction which is an alias of UBFM and is part of Bitfield instructions of Data Processing - Immediate (DPI)
https://developer.arm.com/documentation/ddi0602/2023-12/Base-Instructions/LSR--immediate---Logical-Shift-Right--immediate---an-alias-of-UBFM-
`make all` including conformance testing.
There is a specific rand function to add LSR immediate instructions. However, the conformance test output shows mostly UBFX and UBFIZ and a few LSR and LSL in the output. I think the specific function is not being called.

LSR (alias of UBFM) in Data Processing Immediate.

---

Arm/Decode.lean
Arm/Decode/DPR.lean
Arm/Exec.lean
Arm/Insts/Common.lean
Arm/Insts/DPR/Data_processing_one_source.lean
Arm/Insts/DPR/Insts.lean
Arm/Insts/DPSFP/Advanced_simd_two_reg_misc.lean
Tests/SHA512ProgramTest.lean

This PR adds support for REV, REV16 and REV32 from the [Data processing (1 source) ](https://developer.arm.com/documentation/ddi0602/2023-12/Index-by-Encoding/Data-Processing----Register?lang=en#dp_1src) class. 
The `make all` succeeds and conformance testing runs successfully on Graviton2 and Graviton3.

Add data processing (1 source) class for REV

---

Arm/Decode.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/Common.lean
Arm/Insts/DPSFP/Advanced_simd_copy.lean
Arm/Insts/DPSFP/Advanced_simd_permute.lean
Arm/Insts/DPSFP/Advanced_simd_scalar_copy.lean
Arm/Insts/DPSFP/Advanced_simd_three_different.lean
Arm/Insts/DPSFP/Advanced_simd_three_same.lean
Arm/Insts/DPSFP/Insts.lean

This PR adds support for `[TRN1](https://developer.arm.com/documentation/ddi0602/2023-12/SIMD-FP-Instructions/TRN1--Transpose-vectors--primary--?lang=en)` and `TRN2` from class Advanced SIMD permute.
In addition, it refactors code involving [Elem (non-assignment form) and Elem (assignment form)](https://developer.arm.com/documentation/ddi0602/2023-12/Shared-Pseudocode/shared-functions-common?lang=en#impl-shared.Elem.read.3). This reduces duplicated code and some unnecessary lemmas.
The `make all` succeeds and conformance testing runs successfully on Graviton2 and Graviton3.

Add Advanced SIMD permute class for TRN1 and TRN2

---

Arm/Decode.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/DPSFP/Advanced_simd_copy.lean
Arm/Insts/DPSFP/Advanced_simd_table_lookup.lean
Arm/Insts/DPSFP/Insts.lean

This PR adds support for [TBL/TBX (single, two, three, four register table)](https://developer.arm.com/documentation/ddi0602/2023-12/SIMD-FP-Instructions/TBL--Table-vector-Lookup-?lang=en#TBL_asimdtbl_L1_1) from the Advanced SIMD table lookup class.
The `make all` succeeds and conformance testing runs successfully on Graviton2 and Graviton3.

Add support for TBL/TBX from Advanced SIMD table lookup class

---

Arm/Decode.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/DPSFP/Advanced_simd_scalar_copy.lean
Arm/Insts/DPSFP/Crypto_aes.lean
Arm/Insts/DPSFP/Insts.lean

This PR adds support for [AESE](https://developer.arm.com/documentation/ddi0602/2023-12/SIMD-FP-Instructions/AESE--AES-single-round-encryption-?lang=en) and [AESMC](https://developer.arm.com/documentation/ddi0602/2023-12/SIMD-FP-Instructions/AESMC--AES-mix-columns-?lang=en) from the Cryptographic AES class.
The `make all` succeeds and conformance testing runs successfully on Graviton2 and Graviton3.

Add AESE and AESMC from Cryptographic AES class

---

Arm/BitVec.lean
Arm/Decode.lean
Arm/Decode/DPR.lean
Arm/Decode/DPSFP.lean
Arm/Exec.lean
Arm/Insts/Common.lean
Arm/Insts/DPR/Data_processing_two_source.lean
Arm/Insts/DPR/Insts.lean
Arm/Insts/DPSFP/Advanced_simd_scalar_shift_by_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_shift_by_immediate.lean
Arm/Insts/DPSFP/Insts.lean

1. Added [advanced SIMD scalar shift by immediate](https://developer.arm.com/documentation/ddi0602/2023-12/Index-by-Encoding/Data-Processing----Scalar-Floating-Point-and-Advanced-SIMD?lang=en) instructions: SHL, SSHR and USHR, SSRA and USRA, SRSHR and URSHR, SRSRA and URSRA)
2. Added [advanced SIMD (vector) shift by immediate ](https://developer.arm.com/documentation/ddi0602/2023-12/Index-by-Encoding/Data-Processing----Scalar-Floating-Point-and-Advanced-SIMD?lang=en) instructions: SHL, SSHR and USHR, SSRA and USRA, SRSHR and URSHR, SRSRA and URSRA)
3. Added [data processing two source](https://developer.arm.com/documentation/ddi0602/2023-12/Index-by-Encoding/Data-Processing----Register?lang=en) class for variable shifts (LSLV, LSRV, ARSV, RORV 32-, 64-bit)
The `make all` succeeds and …

Add shift related instructions

---

Arm/BitVec.lean
Arm/Cosim.lean
Arm/Map.lean
Arm/MinTheory.lean
Arm/State.lean
Proofs/MultiInsts.lean
Proofs/Sha512_block_armv8.lean
Proofs/Test.lean
Tactics/Sym.lean
Tests/LDSTTest.lean
Tests/SHA512ProgramTest.lean

Change the program type to `Map` (courtesy @aqjune-aws).
Before this change, the `program` field in `ArmState` had the following type:
`Store (BitVec 64) (Option (BitVec 32))`
Now its type is:
`Map (BitVec 64) (BitVec 32)`
An immediate fallout is that the precondition for symbolic simulation/code reasoning will now become:
`s0.program = <program_map>`
instead of
`s0.program = <program_map>.find?`
`make all` succeeded.

Change the program type in `ArmState` to `Map` 

---

.gitignore
Arm/Insts/LDST/Advanced_simd_multiple_struct.lean
Tests/Debug.lean
Tests/SHA512ProgramTest.lean
lean-toolchain

Building blocks for utilities to trace the ArmState during concrete simulations.
`make all` succeeded.

Functions to trace ArmState during concrete simulations

---

Arm/BitVec.lean
Tests/AES-GCM/AESGCMProgramTests.lean
Tests/AES-GCM/AESV8ProgramTests.lean
Tests/AES-GCM/GCMProgramTests.lean
Tests/Common.lean

This PR removes the definition of List.create:
`List.create (x : BitVec n) (len: Nat) : List (BitVec n)`
and instead uses `List.replicate` from the Lean library.
Due to better support in Lean for the length of the return value from `List.replicate`, a lot of the `have` lemmas for reasoning about length of `List.create` results are no longer needed. Therefore the code is simplified.
Some of the test vectors in Tests/AES-GCM/AESGCMProgramTests.lean are large and we are hitting default `maxRecDepth`, so it is set to higher (512->2100) in that file. 
`make all` and conformance testing was successful

Use List.replicate instead of List.create

---

Arm/BitVec.lean
Arm/Insts/Common.lean
Arm/Insts/DPR/Logical_shifted_reg.lean
Proofs/Simple.lean

Added a new proof using symbolic simulation tactic to prove the simple program "EOR x0 x0 x0" results in register x0 being zero.
What tests have been run? Did `make all` succeed for your changes? 
Yes

Add Simple Proofs (EOR)

---

Arm/BitVec.lean
Specs/GCMV8.lean
Specs/Specs.lean
Tests/AES-GCM/GCMGmultV8Program.lean

This PR adds specification for the three GCMV8 functions including:
`GCMInitV8` for `gcm_init_v8`, `GCMGmultV8` for `gcm_gmult_v8` and `GCMGhashV8` for `gcm_ghash_v8`.
These specification should later be used for establishing correctness of their respective Arm assembly routines.
Make all succeeds and cosimulation tests are successful on Graviton2 and Graviton3 machines.

Add specification for GCMV8 functions

---

Arm/BitVec.lean
Arm/Insts/Common.lean
Arm/Insts/DPI/Bitfield.lean
Makefile

Add support for all `DPI.Bitfield` instructions. Also fix a typo in the Makefile re. cosimulation invocation.
`make all` and conformance testing succeeded.

Add support for all DPI.Bitfield instructions

---

Arm/Insts/Common.lean

`AddWithCarry` now avoids bitvector->Nat and bitvector->Int conversions, making it amenable to bitblasting via LeanSAT.
`make all` succeeded. Also, conformance testing was successful on a Graviton2 machine.

Rewrite `AddWithCarry`

---

Arm/BitVec.lean
Arm/Insts/Common.lean
Arm/Insts/DPI/Bitfield.lean
Arm/Insts/DPI/Logical_imm.lean
Arm/Insts/DPI/Move_wide_imm.lean
Arm/Insts/DPR/Data_processing_one_source.lean
Arm/Insts/DPR/Logical_shifted_reg.lean
Arm/Insts/DPSFP/Advanced_simd_extract.lean
Arm/Insts/DPSFP/Advanced_simd_modified_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_table_lookup.lean
Arm/Insts/DPSFP/Advanced_simd_three_different.lean
Arm/Insts/DPSFP/Conversion_between_FP_and_Int.lean
Arm/Insts/LDST/Advanced_simd_multiple_struct.lean
Arm/Insts/LDST/Reg_imm.lean
Arm/Insts/LDST/Reg_pair.lean
Arm/Insts/LDST/Reg_unscaled_imm.lean
Proofs/SHA512/Sha512_block_armv8_rules.lean
Specs/AESArm.lean
Specs/AESCommon.lean
Specs/GCM.lean
Specs/GCMV8.lean
Tests/AES-GCM/AESGCMProgramTests.lean
Tests/AES-GCM/AESV8ProgramTests.lean
Tests/AES-GCM/GCMProgramTests.lean
Tests/Common.lean
Tests/SHA2/SHA512ProgramTest.lean

Use of `BitVec.cast` is preferred instead of `\t`. This PR rewrites uses of `\t` to `BitVec.cast`. 
In doing so, it causes the theorem `sha512h_rule_2` in `Proofs/SHA512/Sha512_block_armv8_rules.lean` to fail. This is because extra `BitVec.cast` is introduced into the goal that could not be recognized by `bv_decide`. By simplifying the goal using rule `BitVec.cast_eq`, `BitVec.cast` is removed from the goal and the theorem goes through again.
"make all" and cosimulation on Graviton2 and Graviton3 succeed.

Use BitVec.cast instead of \t

---

Tests/AES-GCM/GCMSpecTests.lean
Tests/LDSTTest.lean
Tests/Tests.lean

This PR adds tests for GCMV8 functions including `GCMInitV8`, `GCMGmultV8` and `GCMGhashV8`. These serves as examples for showing the relationship between the specification and the ARM assembly functions. 
"make all" succeeds and cosimulation test succeeds on Graviton2 and Graviton3 machines.

Add tests for GCMV8 spec functions

---

LNSym.code-workspace

This makes it easy(er) to launch a new VSCode instance on a fresh machine, by pointing it to `code LNSym.code-workspace`. Discovered this necessity when setting a new laptop!

chore: add code workspace for first time use of repo

---

Specs/AESV8.lean
Specs/Specs.lean
Tests/AES-GCM/AESV8SpecTests.lean
Tests/Tests.lean

This PR adds specification for AESV8 functions including `AESHWSetEncryptKey`, `AESHWEncrypt` and `AESHWCtr32EncryptBlocks`.
"make all" succeeds and cosimulation test succeeds on Graviton2 and Graviton3 machines.

Add specification for AESV8 functions

---

Arm/Cosim.lean
Arm/State.lean
Correctness.lean
Correctness/Basic.lean
Correctness/Correctness.lean
Correctness/Iterate.lean
Makefile
Tests/AES-GCM/AESGCMProgramTests.lean
Tests/AES-GCM/AESV8ProgramTests.lean
Tests/AES-GCM/GCMProgramTests.lean
Tests/LDSTTest.lean
Tests/SHA2/SHA512ProgramTest.lean
lakefile.lean

Partial correctness can be proved by discharging verification conditions.
`make all` succeeds.

Add general statements/proofs for partial/total correctness

---

.github/workflows/doc.yml

We install cadical in the doc-gen CI to prevent build failures: https://github.com/leanprover/LNSym/actions/runs/10252790764/job/28363964048

chore: install cadical in CI

---

Arm/Cosim.lean

This fixes a conformance testing error introduced in #51, by reading the full 128 bits of an SFP register instead of only the lower 64
Conformance testing passed

fix: read the full 128 bits of an SFP register in cosimulation

---

Tactics/Sym.lean

We establish some minor documentation and tracing for the `sym1_i_n` tactic.
Furthermore, we add a simple `simp` pre-processing step to `sym1_i_n`, 
so that it can also deal with hypotheses stated using the more idiomatic `read_err`/`read_pc` family of functions.
This pre-processing happens only once, before starting symbolic evaluation, and should thus not have any significant performance impact.
`make all` passes, including conformance testing

chore: docs and tracing for `sym1_i_n` tactic

---

Arm/Decode.lean
Arm/Decode/DPR.lean
Arm/Exec.lean
Arm/Insts/DPR/Data_processing_three_source.lean
Arm/Insts/DPR/Insts.lean

Adding support for MADD (32- and 64-bit) instructions.  MUL is an alias.
_**HAVE NOT RUN CONFORMANCE**_

Adding MADD (32- and 64-bit) (alias MUL) to instructions

---

Proofs/AES-GCM/GCMGmultV8Sym.lean
Tactics/Sym.lean
Tactics/SymContext.lean

This refactors the symbolic evaluation using pre-generated theorems to maintain a context structure which tracks the names of the various theorems needed for eval, rather than relying on these theorems to be available with hard-coded names.
In the process, we also define a way to infer the initial context by searching through the local context for variables and hypothesis that are def-eq to what we expect (basically doing `by assumption`). This has two big benefits:
* It allows us to generate more meaningful error messages when the contract is broken, and
* During this search we also infer and assert more information. For example, we assert that the `m` in `sf = run m s0` is a numeric literal and reflect the value (we can use this in future to throw a meaningful error when the user asks …

feat: introduce `sym1_n` tactic as a more intelligent version of `sym1_i_n`

---

Proofs/AES-GCM/GCMGmultV8Sym.lean
Tactics/Sym.lean
Tactics/SymContext.lean
Tests/Tactics/Sym.lean

Expands upon #69 to include context search for `h_err` and `h_sp`.
These assumptions are not strictly required, since we don't reflect information from them, 
so if they are not present we  introduce a new goal for them (in contrast to the other hypotheses, for which we simply throw an error).
`make all` succeeds, including conformance testing

feat: make sym_n search for h_err and h_sp, or introduce new goals if they are not present

---

Proofs/AES-GCM/GCMGmultV8Sym.lean
Proofs/Experiments/AbsVCG.lean
Proofs/Popcount32.lean
Proofs/SHA512/Sha512DecodeExecLemmas.lean
Proofs/SHA512/Sha512FetchLemmas.lean
Proofs/SHA512/Sha512StepLemmas.lean
Tactics/StepThms.lean

Change `#genStepTheorems` theorem generation so that the generated theorems are put in the namespace of the program they belong to.
This removes the need for the user to pick a prefix, but most importantly, gives these theorems predictable names, so that other automation (i.e., `sym_n`) knows where to find them.
`make all` succeeds, I've not run conformance testing, since I haven't changed any definitions

refactor: generate `stepi` theorems in the relevant program's namespace

---

Arm/Cosim.lean
Arm/Insts/Cosim/disasm.sh
Arm/Insts/Cosim/platform_check.sh
Arm/Insts/Cosim/simulator.c

Cosimulation can now be run on Arm-based Apple machines.
`make all` and conformance testing succeeded on an Apple M3 machine and an Amazon Linux Graviton2 machine.

Modify cosim scripts to work on M* Apple machines

---

Proofs/Experiments/SHA512MemoryAliasing.lean
Proofs/Popcount32.lean
Proofs/SHA512/Sha512Sym.lean
Tactics/Common.lean
Tactics/StepThms.lean
Tactics/Sym.lean
Tactics/SymContext.lean

A collection of non-functional refactors to the `Sym` and `SymContext` files among which:
- Introduce `SymContext.next_state` to generate the name for the next intermediate state
- Rename `h_err`/`h_sp` fields to `h_err?`/`h_sp?` to reflect they are options, and introduce `h_err`/`h_sp` functions with a hard-coded default value
- Reduce the use of full-qualified names, through `open`
- Deprecate `sym1_i_n` (which uses hard-coded names) in favour of `sym1_n` (which searches the local context)
`make all` runs locally

refactor: assorted cleanups of `Sym`/`SymContext`

---

Proofs/Experiments/AbsVCG.lean
Proofs/Popcount32.lean
Proofs/SHA512/Sha512DecodeExecLemmas.lean
Tactics/StepThms.lean

Some stepi-theorems were being generated which still included elements like `decode_bit_masks 0#1 3#6 0#6 false`.
After investigation, I noticed simprocs were *not* being passed to `simp` in `StepThms`, so I fixed that.
`make all` ran locally

fix: use simprocs in step-theorem generation

---

Arm/BitVec.lean
Arm/MinTheory.lean
Proofs/Experiments/AbsVCG.lean
Proofs/Popcount32.lean
Proofs/SHA512/Sha512DecodeExecLemmas.lean
Proofs/SHA512/Sha512StepLemmas.lean
Tactics/StepThms.lean

Relatively minor PR: adds some existing lemmas to the `minimal_theory` and `bitvec_rules` to get nicer normal forms. 
In particular:
- `BitVec.zero` now becomes `0#_`, and
- `truncate` now becomes `zeroExtend`, since the latter has simprocs for better reduction
Various tests have been changed accordingly
`make all` ran locally

Better bitvec reduction

---

Arm/Cosim.lean
Arm/Insts/Common.lean
Arm/Insts/Cosim/platform_check.sh
Arm/Insts/DPI/Add_sub_imm.lean
Arm/Insts/DPI/Bitfield.lean
Arm/Insts/DPI/Logical_imm.lean
Arm/Insts/DPI/Move_wide_imm.lean
Arm/Insts/DPR/Add_sub_carry.lean
Arm/Insts/DPR/Add_sub_shifted_reg.lean
Arm/Insts/DPR/Conditional_select.lean
Arm/Insts/DPR/Data_processing_one_source.lean
Arm/Insts/DPR/Data_processing_three_source.lean
Arm/Insts/DPR/Data_processing_two_source.lean
Arm/Insts/DPR/Logical_shifted_reg.lean
Arm/Insts/DPSFP/Conversion_between_FP_and_Int.lean
Arm/Insts/DPSFP/Crypto_four_reg.lean
Arm/Insts/DPSFP/Crypto_three_reg_sha512.lean
Arm/Insts/DPSFP/Crypto_two_reg_sha512.lean

Workaround to avoid clobbering `x18` and `x29` on Apple's Arm machines.
`make all` ran on my M3 and a Graviton2 machine.

Respect Apple's ABI for cosimulations

---

Arm/Cosim.lean
Arm/Insts/Common.lean
Arm/Insts/DPI/Add_sub_imm.lean
Arm/Insts/DPI/Bitfield.lean
Arm/Insts/DPI/Logical_imm.lean
Arm/Insts/DPR/Add_sub_carry.lean
Arm/Insts/DPR/Add_sub_shifted_reg.lean
Arm/Insts/DPR/Conditional_select.lean
Arm/Insts/DPR/Data_processing_one_source.lean
Arm/Insts/DPR/Data_processing_three_source.lean
Arm/Insts/DPR/Data_processing_two_source.lean
Arm/Insts/DPR/Logical_shifted_reg.lean
Arm/Insts/DPSFP/Conversion_between_FP_and_Int.lean

`x18` is not used either as a source or destination register. Moreover, it is not expected to be preserved after a cosim test.
This is expected to clear up the bogus mismatches we see on Arm-based Apple machines.
Another relevant PR: https://github.com/leanprover/LNSym/pull/98 
`make all` succeeds on my M3.

Avoid `x18` entirely on Arm-based Apple machines

---

Main.lean
Makefile

I realized that I was never really running cosim locally because it took too long --- in an effort to remedy the situation, I set `make` (the default `make all`) rule to run `quick-cosim`, which sets `--num-tests=3`. While this is still a tad too long for my taste, it is, at the very least, tolerable, so I actually run cosim locally now rather than relying on CI (: 

chore: make cosim quicker on default build

---

Arm/BitVec.lean
Arm/Memory/Separate.lean

This PR peels the bitvector library features from
https://github.com/leanprover/LNSym/pull/90/,
with theorems for `extractLsBytes`.
This enables us to rewrite proofs about reading and writing bytes in memory with a higher level API.

feat: extractLsBytes and related proofs for simp_mem [1/3?]

---

Arm/Insts/DPSFP/Advanced_simd_copy.lean

Use `GPRIndex.rand` for a few instructions that I overlooked in #103
`make all` succeeds on my M3.

Use GPRIndex.rand in some more places

---

Proofs/SHA512/SHA512Sym.lean

Construct test to check progress of our symbolic simulation/cse tactics. 
`make all` succeeded on my M3.

Test for symbolic simulation of SHA512 (1 message block)

---

Proofs/SHA512/SHA512Sym.lean
Tactics/CSE.lean

This fixes the bug reported by @shigoel, where we would get a `no goals to be solved` failure after the `cse` tactic was run on all hypotheses --- we were incorrectly backtracking, which is fixed now. 
The next PRs will improve scaling issues by the following:
1. adding a custom amount of fuel that will allow the CSE tactic to stop gracefully.
2. Not CSEing small objects such as `Nat` literals which are ubiquitous, as well as pointless to CSE.
We will also make improvements to debug logging in a separate commit. 
Thus, we anticipate this patch set to have four patches, which will be peeled from https://github.com/leanprover/LNSym/pull/113

chore: checkpoint tactic state before  in CSE and restore on failure [1/4?]

---

Arm/Insts/Common.lean
Arm/Insts/DPI/Logical_imm.lean
Specs/GCMV8.lean

Fix spec. of `DPI.Logical_imm` instructions to account for the behavior of `ORR`'s alias `MOV` and `ANDS`'s alias `TST`.
`make all` succeeded on my M3.

Fix DPI.Logical_imm instructions to account for aliases TST and MOV

---

Tactics/Aggregate.lean

Adds the option to simp-aggregate effects at a specific local hypothesis, using `sym_aggregate at h_foo` as the syntax.
`make_all` ran locally

feat: add `at _` location option to `sym_aggregate`

---

.gitignore

I noticed that VScode now has a `.vscode/` folder for me, which holds workspace-specific settings. Add this folder into `.gitignore` to prevent accidental check-ins

chore: add .vscode/ to gitignore

---

Arm/BitVec.lean

I've opened [#5375](https://github.com/leanprover/lean4/pull/5375) upstream, but in the meantime we can add the normalization rule ourselves. This ensures we don't have to get rid of uses of the `ofBool (getLsb ..)` pattern in #159

feat: ofBool_getLsbD normalization rule for bv_decide

---

Arm/State.lean
Proofs/Popcount32.lean
Tactics/Aggregate.lean

Prove that the popcount32 program correctly computes the bitcount of its input, and prove that certain state components were left unmodified by this program.
`make all` ran locally.

Popcount32 functional correctness and (non)effects characterization

---

Arm/BitVec.lean

We add lemmas about (non) overflow, as well as theorems that show that not-equals-zero iff equals-one

feat: bitvec lemmas for `memcpy` [1/? memcpy]

---

Tactics/SkipProof.lean

Surrounding a tactic with `skip_proof` will skip running the tactic and close the goal with `skipProofAx`.
We only skip proofs `skip_proof.skip` is set to `true`, and we emit a warning to remind the user that proofs are being skipped.
This is to be used, during development, with expensive tactics such as `omega`, `bv_omega`, `bv_decide`, `simp_mem`.
This allows one to run `have expensive_hyp : ... := by omega`, check that this can be proven,
and to then replace this with `have expensive_hyp : ... := by skip_proof omega`,
which will skip the use of `omega`, and instead of `skipProoxAx`, ensuring Lean stays interactive. 
This makes `skip_proof p` morally different from a `sorry`:
- It still retains the proof `p`. This signals the intent of a completed proof that has been skipped for …

feat: add tactic to skip proof checking during development. [PR 5/? for memcpy]

---

Arm/Memory/Separate.lean

We use this to allow `#eval decide (mem_subset' 10 100 10 100)` for interactive use-cases, and for proofs, where these goals can be dispatched by `decide`.
conformance testing successful on an Aarch64 machine? 
`make all` succeeds, conformance succeeds locally.

feat: Decidable instances for mem_legal', mem_subset', mem_separate'

---

Tactics/CSE.lean
Tactics/Reflect/ProgramInfo.lean
Tests/Tactics/CSE.lean

This fixes deprecation warnings telling us to switch to `Std.HashMap

chore: Switch to Std.HashMap

---

Arm/Insts/Common.lean
Arm/Insts/DPI/Add_sub_imm.lean
Arm/Memory/SeparateProofs.lean
Proofs/Experiments/AddLoop/AddLoop.lean
Proofs/Experiments/Max/MaxTandem.lean
Proofs/Popcount32.lean
Proofs/SHA512/SHA512Sym.lean

This works around https://github.com/leanprover/lean4/issues/5388, and removes uses of `simp (config := { ground := true }) ..`. This makes our proof states cleaner, since we no longer see proof states involving `Decidable.rec ...`. Peeled from #168 
`make all` succeeded, conformance succeeded.

chore: rewrite semantics to not have pattern match on structure

---

Arm/BitVec.lean
Arm/Decode.lean
Arm/Exec.lean
Arm/Insts/DPSFP/Advanced_simd_two_reg_misc.lean
Arm/MinTheory.lean
Arm/State.lean
Correctness/Correctness.lean
Proofs/Experiments/SHA512MemoryAliasing.lean
Specs/GCMV8.lean

This PR changes well-founded recursion to structural recursion in several functions and this allows us to use `rfl` for the tests that associate with these functions.
Relevant PR: https://github.com/leanprover/LNSym/pull/151
conformance testing successful on an Aarch64 machine? yes

Use structural recursion and rfl

---

.github/workflows/doc.yml
.github/workflows/makefile.yml
README.md

Cadical is no longer a user-facing dependency of LNSym, now that it is available with Lean.
Yes

Remove cadical build/install in workflows

---

.github/workflows/copyright-header.yml
Arm/Attr.lean
Arm/FromMathlib.lean
Arm/MinTheory.lean
Proofs/SHA512/SHA512.lean
lakefile.lean

Add a workflow to check whether the Copyright header is present in all Lean files (borrowed from [Lean's own workflow](https://github.com/leanprover/lean4/blob/master/.github/workflows/copyright-header.yml)).
Yes.

Add workflow to check for presence of copyright headers

---

Tactics/Sym.lean
Tactics/SymContext.lean

Continues the cleanup started in #180 by getting rid of `h_err?` and `addGoalsForMissingHypotheses`.
Note that we remove the ability to add a goal for `CheckSPAlignment`, this option was false by default, and never used
conformance testing successful on an Aarch64 machine? yes

refactor: remove `SymContext.h_err?` field, move `addGoalsForMissingHypotheses` functionality into `fromLocalContext`

---

Arm/Memory/SeparateAutomation.lean
Proofs/Experiments/Memcpy/MemCpyVCG.lean
Proofs/Experiments/MemoryAliasing.lean

We noticed that `simp_mem` required way too many heartbeats, so we change it to be less agressive.
In future, based off of work in https://github.com/leanprover/LNSym/pull/184, we shall introduce a different tactic call `mem_omega` to close `omega` style goals, and making `simp_mem` (i.e., the internal rewriter within the symbolic simulation) to only perform rewriting, not goal-closing. 
Conformance succeeds.

chore: make simp_mem less aggressive, was timing out

---

Arm/Memory/SeparateAutomation.lean
Proofs/Experiments/MemoryAliasing.lean
Proofs/Experiments/SHA512MemoryAliasing.lean

We want to reuse as much of `bv_omega` as possible, and implement `bv_omega` within `simp_mem` by calling the appropriate `simp` and `omega` meta level functions, with the goal of extracting the counter-example model from `omega` for lazy unfolding (ala CEGAR). To do this, we first delete our layers on top of `bv_omega`. The next patch in the series will replace the call of `evalTactic (tactic| bv_omega)` with the appropriate meta-level functions.  This will allow us to inspect the state of `bv_omega`, instead of it being a black-box tactic invocation.
This is a chore PR.
Conformance succeeds. 
made …

chore: delete bv_omega', reuse bv_omega

---

Benchmarks/Command.lean

The `geomean` computation that was incorrectly suggested by @bollu failed to take into account that the `TotalRunTime` counter was adding the real runtimes, not multiplying them as one should for geomean.
We change the `geomean` computation algorithm, to accumulate the `log` of the runtimes, and then divide by `n` followed by exponentiation as a final step for better numerical accuracy.
$$
g \equiv (t_1 \times t_2 \times \dots \times t_n)^{1/n} = \exp \bigg(\frac{\log t_1 + \log t_2 + \dots \log t_n}{n} \bigg)
$$
Conformance succeeds.

chore: fix geomean computation

---

Tactics/SymContext.lean

We claim in the error that we fall back to `s1` as the first intermediate state if we can't infer anything. 
However, the implementation actually used `s2`. 
This PR fixes that by setting `currentStateNumber := 0` in the fallback case. The off-by-one behaviour is because this number is incremented *before* it's used to generate a new state.

fix: `inferStatePrefix...` should default to `s1` as the first intermediate state.

---

Arm/State.lean
Arm/Syntax.lean
Proofs/Popcount32.lean
Tactics/StepThms.lean

Introduce syntax for stating register and memory frame conditions, which specify exactly which state components are not affected by the program's execution.
The popcount proof is modified to use this new syntax.
Also: use `gen_step.print_names` option to print generated stepi theorems' names.
Yes

Syntax for stating register and memory frame conditions

---

Benchmarks/SHA512_150.lean
Benchmarks/SHA512_225.lean
Benchmarks/SHA512_400.lean
Tactics/Common.lean
Tactics/Sym/Context.lean

Stacked on #189, we use the more powerful search capabilities to include hypotheses that describe reads from *any* `StateField` into the initial AxEffects.

feat: search for reads of *any* register when building an initial `SymContext`

---

Arm/BitVec.lean
Arm/Memory/SeparateAutomation.lean
Proofs/Popcount32.lean

This prevents us from unfolding expressions that have `.toNat` into gigantic expressions. Furthermore, this helps `bv_decide`, since it can see pure bitvector statements.

feat: remove toNat lemmas from bitvec_rules

---

Arm/BitVec.lean
Arm/Insts/Common.lean
Arm/Insts/DPI/Move_wide_imm.lean
Arm/Insts/DPI/PC_rel_addressing.lean
Arm/Insts/DPSFP/Advanced_simd_copy.lean
Arm/Insts/DPSFP/Advanced_simd_permute.lean
Arm/Insts/DPSFP/Advanced_simd_table_lookup.lean
Arm/Insts/DPSFP/Advanced_simd_three_different.lean
Arm/Insts/DPSFP/Advanced_simd_three_same.lean
Proofs/SHA512/SHA512_block_armv8_rules.lean
Specs/AESCommon.lean
Specs/AESV8.lean
Specs/GCM.lean
Specs/GCMV8.lean
Tests/Tactics/CSE.lean

This PR simplifies the definition of `partInstall`. Its signature used to be:
```
abbrev partInstall (hi lo : Nat) (val : BitVec (hi - lo + 1)) (x : BitVec n): BitVec n
```
and now it becomes:
```
abbrev partInstall (start len : Nat) (val : BitVec len) (x : BitVec n): BitVec n
```
This follows the same pattern in `extractLsb` vs `extractLsb'`. By doing this, we are able to simplify several functions that depends on `partInstall`.

Simplify partInstall to use start and len

---

Tactics/Sym.lean
Tactics/Sym/Context.lean

Benchmarks suggest this could be marginally slower than before (the SHA512_400 benchmark slowed down from 19.0 to 19.2 second, i.e., within noise levels).
Still, it's a good change to make, because it will make effect aggregation easier.

refactor: remove `SymContext.h_sp?`, replacing uses with the corresponding `AxEffects` field

---

Proofs/SHA512/SHA512_block_armv8_rules.lean

This PR extends `truncate_of_concat_is_lsb_64` to arbitrary-width bitvectors. 
What tests have been run? Did `make all` succeed for your changes? Yes
Was conformance testing successful on an Aarch64 machine? yes 

feat: generalize to arbitrary bitvec width `zeroextend_bigger_smaller` and `truncate_of_concat_is_lsb`

---

Arm/Insts/Common.lean
Tactics/Sym.lean
Tactics/Sym/AxEffects.lean

Stacked on #207.
When an write to memory or a write to a register that is not SP is made, we update the proof of stack alignment. When a write to SP is made, we create a new mvar with the proof obligation that the new value is aligned, and store that mvar in a new `sideConditions` field. 

feat: attempt to preserve stack alignment proof in AxEffect update

---

Arm/Insts/Common.lean
Arm/Insts/DPSFP/Advanced_simd_modified_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_scalar_shift_by_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_shift_by_immediate.lean
Arm/Insts/DPSFP/Advanced_simd_three_different.lean
Proofs/AES-GCM/GCMGmultV8Sym.lean
Proofs/Popcount32.lean
Specs/GCMV8.lean

Some work towards proving the functional correctness of GCM Gmult. 
Summary of changes:
1. Removed `h : esize > 0` from the `ShiftInfo` structure.
2. Added a `dsimproc` for `AdvSIMDExpandImm`. Cleaned up other `dsimproc`s.
3. Defined `GCMGmultV8_alt`, an alternative GCM GMult definition that does not traffic in lists.
4. Massaged the functional correctness goal a bit.
Yes

Work towards the GCM GMult functional correctness proof

---

Tactics/Common.lean
Tactics/Sym/AxEffects.lean
Tactics/Sym/Common.lean
Tactics/Sym/Context.lean
Tactics/Sym/MemoryEffects.lean

Extracted from #179, stacked on #220.
We extract out memory-effects related code from AxEffects into a new MemoryEffects structure. This PR is purely a non-functional change, but will serve as the starting point of integrating simp_mem with sym_n.
The current simplification is effectively a no-op, since the proof state is not massaged to the way `simp_mem` wants it to be. Subsequent PRs will focus on massaging the goal state to be as `simp_mem` likes, and then trying to symbolically simplify the memory expression we see.
conformance testing successful on an Aarch64 machine? yes
Co-authored-by …

refactor: extract out `MemoryEffects` structure

---

Arm/Memory/SeparateAutomation.lean
Proofs/Experiments/MemoryAliasing.lean

fixes #115
This was a really interesting bugfix, and was my bug. The `simp_mem` tactic tries to handle hypotheses of the form `mem.read addr1 n1 = mem.read addr2 n2` by registering both sides as useful information that it should exploit.
However, the part that flips the equality forgot to flip the equality :) 
Debugging this was enormously painful, because for whatever reason, the kernel spends an enormously long time checking the proof, and then gives up with "deterministic timeout". Regardless, here's the patch that fixes it:
```diff
@@ -314,7 +305,7 @@ we can have some kind of funny situation where both LHS and RHS are ReadBytes.
For example, `mem1.read base1 n = mem2.read base2 n`.
In such a scenario, we should record both reads.
-/
-def ReadBytesEqProof.ofExpr? (eval : Expr) (etype : …
```

chore: fix proof building in 'mem.read ... = mem.read ...'

---

Arm/Memory/Separate.lean

Closes https://github.com/leanprover/LNSym/issues/137
We prove `mem_separate_of_mem_separate'`, showing that the old defn aligns with the new defn for non-zero-width-inervals.
We do not change any executable defs, and cosim succeeds.

feat: mem_separate_of_mem_separate'

---

Proofs/SHA512/SHA512Prelude.lean
Tactics/Aggregate.lean

Resolves a [TODO in SHA512Prelude](https://github.com/leanprover/LNSym/blob/2e4d59cbd6f76eb8d63ed41ccbda38b49dd9c7ae/Proofs/SHA512/SHA512Prelude.lean#L144)
We add the capability for `sym_aggregate` to rewrite along hypotheses about the program of an ArmState.

feat: expand `sym_aggregate` search to include equalities `?state.program = ?program`

---

Tactics/Attr.lean
Tactics/Sym.lean
Tactics/Sym/AxEffects.lean
Tactics/Sym/Common.lean
Tactics/Sym/Context.lean

We rename `Tactic.sym.debug` to `Tactic.sym.info` to be consistent with the `simp_mem.info` traceclass. Also, we rename `withVerboseTraceNode` to `withInfoTraceNode` to explicitly refer to the new name, and ensure it uses the right trace class (rather than the non-existent `Tactic.sym.verbose`)

refactor: rename `Tactic.sym.debug` traceclass to avoid confusion with the option of the same name.

---

Tactics/BvOmegaBench.lean

This allows us to gradually convert all our tactics to `MetaM`,
which provides the correct level to discipline to make sure
that bugs like https://github.com/leanprover/LNSym/issues/154 don't happen anymore.
Also, as a mild bonus, one hopes that eliminating `evalTactic` makes stuff a bit faster,
but I would not hold my breath on this.
Stacked on #231 

feat: Switch bvOmegaBench to use MetaM [3/?]

---

Arm/Memory/Common.lean
Arm/Memory/MemOmega.lean
Tactics/BvOmegaBench.lean

This ensures that one part of the infrastructure is written
completely in terms of MetaM. We will give `simp_mem` the same
treatment next.
PR stacked on top of https://github.com/leanprover/LNSym/pull/232
No executable defs have changed, cosim succeeds.

feat: Switch out all of `mem_omega` with MetaM [4/?]

---

Arm/Memory/MemOmega.lean
Arm/Memory/SeparateAutomation.lean
Proofs/Experiments/Memcpy/MemCpyVCG.lean
Proofs/Experiments/MemoryAliasing.lean

We increase the ITPness of `simp_mem` by making it less of a proof hammer, and more of a user-controllable rewrite engine. Description of the new design follows:
----
The simp_mem tactic allows simplifying expressions of the form `Memory.read_bytes rbase rn (mem')`.
`simp_mem` attempts to discover the result of the expression by various heuristics,
which can be controlled by the end user:
- (a) If `mem' = Memory.write_bytes wbase wn mem` and we know that `(rbase, rn) ⟂ (wbase, wn)`, then we simplify to `mem.read (rbase, rn)`.
- (b) If `mem' = Memory.write_bytes wbase wn wval mem` and we kow that `(rbase, rn) ⊆ (wbase, wn)`, then we simplify to `wval.extract (rbase, rn) (wbase, wn)`.
- (c) If we have a hypothesis `hr' : mem'.read_bytes  rbase' rn' = rval`, and we know that `(rbase, rn) ⊆ …

feat: Add fine grained control over mem_omega rewriting [7/?]

---

Arm/Memory/Common.lean
Arm/Memory/MemOmega.lean
Arm/Memory/SeparateAutomation.lean
Proofs/AES-GCM/GCMGmultV8Sym.lean
Proofs/Experiments/Memcpy/MemCpyVCG.lean
Proofs/Experiments/MemoryAliasing.lean
Proofs/Experiments/SHA512MemoryAliasing.lean
Proofs/SHA512/SHA512Prelude.lean
Tactics/BvOmegaBench.lean

This adapts changes made in #238 for `mem_omega` into `simp_mem`. This adds a ITP style mode into `simp_mem`, which receives user guidance and attempts to proceed according to user input. It throws errors if the goal state does not match the expected goal state. If the goal state matches, it tries to dischange side conditions automatically. Failing this, it creates new goals for the user to discharge these side conditions. In total, this converts `simp_mem` into a tactic that's usable for making incremental, interactive progress in simplifying memory non-interference.
No semantics changed. Conformance succeeds. 
---
Stacked on top of #238 
By submitting this pull …

feat: enable simp_mem to be used in ITP style [8/?]

---

Proofs/AES-GCM/GCMInitV8Sym.lean

Update the gcm_init_v8 proof by using `Memory.read_bytes` and update the autogenerated `simp only`.
conformance testing successful on an Aarch64 machine? Yes.

Update the gcm_init_v8 proof
